services:
  # Laravel App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drink_shop_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - drink_shop_network
    depends_on:
      - db

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: drink_shop_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - drink_shop_network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: drink_shop_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: drink_shop
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: drink_user
      MYSQL_PASSWORD: drink_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - drink_shop_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: drink_shop_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: drink_user
      PMA_PASSWORD: drink_password
    networks:
      - drink_shop_network
    depends_on:
      - db

volumes:
  db_data:

networks:
  drink_shop_network:
    driver: bridge